const types = @import("types.zig");
const std = @import("std");

pub const aiScene = types.aiScene;
pub const aiNode = types.aiNode;
pub const aiMesh = types.aiMesh;
pub const aiMaterial = types.aiMaterial;
pub const aiAnimation = types.aiAnimation;
pub const aiCamera = types.aiCamera;
pub const aiLight = types.aiLight;
pub const aiTexture = types.aiTexture;
pub const aiString = types.aiString;
pub const aiVector3D = types.aiVector3D;
pub const aiVector2D = types.aiVector2D;
pub const aiMatrix3x3 = types.aiMatrix3x3;
pub const aiMatrix4x4 = types.aiMatrix4x4;
pub const aiQuaternion = types.aiQuaternion;
pub const aiColor4D = types.aiColor4D;
pub const aiColor3D = types.aiColor3D;
pub const aiAABB = types.aiAABB;
pub const aiFace = types.aiFace;
pub const aiBone = types.aiBone;
pub const aiMemoryInfo = types.aiMemoryInfo;
pub const aiPropertyStore = types.aiPropertyStore;
pub const aiLogStream = types.aiLogStream;
pub const aiFileIO = types.aiFileIO;
pub const aiExportDataBlob = types.aiExportDataBlob;
pub const aiExportFormatDesc = types.aiExportFormatDesc;
pub const aiImporterDesc = types.aiImporterDesc;
pub const aiReturn = types.aiReturn;
pub const aiDefaultLogStream = types.aiDefaultLogStream;
pub const aiOrigin = types.aiOrigin;
pub const aiMetadata = types.aiMetadata;
pub const aiMetadataEntry = types.aiMetadataEntry;
pub const aiSkeleton = types.aiSkeleton;
pub const aiSkeletonBone = types.aiSkeletonBone;
pub const aiReal = types.ai_real;
pub const aiBool = types.aiBool;

pub extern "c" fn aiImportFile(pFile: [*:0]const u8, pFlags: c_uint) ?*const aiScene;
pub extern "c" fn aiImportFileEx(pFile: [*:0]const u8, pFlags: c_uint, pFS: ?*aiFileIO) ?*const aiScene;
pub extern "c" fn aiImportFileExWithProperties(pFile: [*:0]const u8, pFlags: c_uint, pFS: ?*aiFileIO, pProps: ?*const aiPropertyStore) ?*const aiScene;
pub extern "c" fn aiImportFileFromMemory(pBuffer: [*]const u8, pLength: c_uint, pFlags: c_uint, pHint: ?[*:0]const u8) ?*const aiScene;
pub extern "c" fn aiImportFileFromMemoryWithProperties(pBuffer: [*]const u8, pLength: c_uint, pFlags: c_uint, pHint: ?[*:0]const u8, pProps: ?*const aiPropertyStore) ?*const aiScene;
pub extern "c" fn aiApplyPostProcessing(pScene: ?*const aiScene, pFlags: c_uint) ?*const aiScene;
pub extern "c" fn aiGetPredefinedLogStream(pStreams: aiDefaultLogStream, file: ?[*:0]const u8) aiLogStream;
pub extern "c" fn aiAttachLogStream(stream: *const aiLogStream) void;
pub extern "c" fn aiEnableVerboseLogging(d: aiBool) void;
pub extern "c" fn aiDetachLogStream(stream: *const aiLogStream) aiReturn;
pub extern "c" fn aiDetachAllLogStreams() void;
pub extern "c" fn aiReleaseImport(pScene: ?*const aiScene) void;
pub extern "c" fn aiGetErrorString() [*:0]const u8;
pub extern "c" fn aiIsExtensionSupported(szExtension: [*:0]const u8) aiBool;
pub extern "c" fn aiGetExtensionList(szOut: *aiString) void;
pub extern "c" fn aiGetMemoryRequirements(pIn: ?*const aiScene, out: *aiMemoryInfo) void;
pub extern "c" fn aiCreatePropertyStore() ?*aiPropertyStore;
pub extern "c" fn aiReleasePropertyStore(p: ?*aiPropertyStore) void;
pub extern "c" fn aiSetImportPropertyInteger(store: ?*aiPropertyStore, szName: [*:0]const u8, value: c_int) void;
pub extern "c" fn aiSetImportPropertyFloat(store: ?*aiPropertyStore, szName: [*:0]const u8, value: aiReal) void;
pub extern "c" fn aiSetImportPropertyString(store: ?*aiPropertyStore, szName: [*:0]const u8, st: *const aiString) void;
pub extern "c" fn aiSetImportPropertyMatrix(store: ?*aiPropertyStore, szName: [*:0]const u8, mat: *const aiMatrix4x4) void;
pub extern "c" fn aiCreateQuaternionFromMatrix(quat: *aiQuaternion, mat: *const aiMatrix3x3) void;
pub extern "c" fn aiDecomposeMatrix(mat: *const aiMatrix4x4, scaling: *aiVector3D, rotation: *aiQuaternion, position: *aiVector3D) void;
pub extern "c" fn aiTransposeMatrix4(mat: *aiMatrix4x4) void;
pub extern "c" fn aiTransposeMatrix3(mat: *aiMatrix3x3) void;
pub extern "c" fn aiTransformVecByMatrix3(vec: *aiVector3D, mat: *const aiMatrix3x3) void;
pub extern "c" fn aiTransformVecByMatrix4(vec: *aiVector3D, mat: *const aiMatrix4x4) void;
pub extern "c" fn aiMultiplyMatrix4(dst: *aiMatrix4x4, src: *const aiMatrix4x4) void;
pub extern "c" fn aiMultiplyMatrix3(dst: *aiMatrix3x3, src: *const aiMatrix3x3) void;
pub extern "c" fn aiIdentityMatrix3(mat: *aiMatrix3x3) void;
pub extern "c" fn aiIdentityMatrix4(mat: *aiMatrix4x4) void;
pub extern "c" fn aiGetImportFormatCount() usize;
pub extern "c" fn aiGetImportFormatDescription(pIndex: usize) ?*const aiImporterDesc;

pub extern "c" fn aiVector2AreEqual(a: *const aiVector2D, b: *const aiVector2D) c_int;
pub extern "c" fn aiVector2AreEqualEpsilon(a: *const aiVector2D, b: *const aiVector2D, epsilon: f32) c_int;
pub extern "c" fn aiVector2Add(dst: *aiVector2D, src: *const aiVector2D) void;
pub extern "c" fn aiVector2Subtract(dst: *aiVector2D, src: *const aiVector2D) void;
pub extern "c" fn aiVector2Scale(dst: *aiVector2D, s: aiReal) void;
pub extern "c" fn aiVector2SymMul(dst: *aiVector2D, other: *const aiVector2D) void;
pub extern "c" fn aiVector2DivideByScalar(dst: *aiVector2D, s: aiReal) void;
pub extern "c" fn aiVector2DivideByVector(dst: *aiVector2D, v: *aiVector2D) void;
pub extern "c" fn aiVector2Length(v: *const aiVector2D) aiReal;
pub extern "c" fn aiVector2SquareLength(v: *const aiVector2D) aiReal;
pub extern "c" fn aiVector2Negate(dst: *aiVector2D) void;
pub extern "c" fn aiVector2DotProduct(a: *const aiVector2D, b: *const aiVector2D) aiReal;
pub extern "c" fn aiVector2Normalize(v: *aiVector2D) void;

pub extern "c" fn aiVector3AreEqual(a: *const aiVector3D, b: *const aiVector3D) c_int;
pub extern "c" fn aiVector3AreEqualEpsilon(a: *const aiVector3D, b: *const aiVector3D, epsilon: f32) c_int;
pub extern "c" fn aiVector3LessThan(a: *const aiVector3D, b: *const aiVector3D) c_int;
pub extern "c" fn aiVector3Add(dst: *aiVector3D, src: *const aiVector3D) void;
pub extern "c" fn aiVector3Subtract(dst: *aiVector3D, src: *const aiVector3D) void;
pub extern "c" fn aiVector3Scale(dst: *aiVector3D, s: aiReal) void;
pub extern "c" fn aiVector3SymMul(dst: *aiVector3D, other: *const aiVector3D) void;
pub extern "c" fn aiVector3DivideByScalar(dst: *aiVector3D, s: aiReal) void;
pub extern "c" fn aiVector3DivideByVector(dst: *aiVector3D, v: *aiVector3D) void;
pub extern "c" fn aiVector3Length(v: *const aiVector3D) aiReal;
pub extern "c" fn aiVector3SquareLength(v: *const aiVector3D) aiReal;
pub extern "c" fn aiVector3Negate(dst: *aiVector3D) void;
pub extern "c" fn aiVector3DotProduct(a: *const aiVector3D, b: *const aiVector3D) aiReal;
pub extern "c" fn aiVector3CrossProduct(dst: *aiVector3D, a: *const aiVector3D, b: *const aiVector3D) void;
pub extern "c" fn aiVector3Normalize(v: *aiVector3D) void;
pub extern "c" fn aiVector3NormalizeSafe(v: *aiVector3D) void;
pub extern "c" fn aiVector3RotateByQuaternion(v: *aiVector3D, q: *const aiQuaternion) void;

pub extern "c" fn aiMatrix3FromMatrix4(dst: *aiMatrix3x3, mat: *const aiMatrix4x4) void;
pub extern "c" fn aiMatrix3FromQuaternion(mat: *aiMatrix3x3, q: *const aiQuaternion) void;
pub extern "c" fn aiMatrix3AreEqual(a: *const aiMatrix3x3, b: *const aiMatrix3x3) c_int;
pub extern "c" fn aiMatrix3AreEqualEpsilon(a: *const aiMatrix3x3, b: *const aiMatrix3x3, epsilon: f32) c_int;
pub extern "c" fn aiMatrix3Inverse(mat: *aiMatrix3x3) void;
pub extern "c" fn aiMatrix3Determinant(mat: *const aiMatrix3x3) aiReal;
pub extern "c" fn aiMatrix3RotationZ(mat: *aiMatrix3x3, angle: aiReal) void;
pub extern "c" fn aiMatrix3FromRotationAroundAxis(mat: *aiMatrix3x3, axis: *const aiVector3D, angle: aiReal) void;
pub extern "c" fn aiMatrix3Translation(mat: *aiMatrix3x3, translation: *const aiVector2D) void;
pub extern "c" fn aiMatrix3FromTo(mat: *aiMatrix3x3, from: *const aiVector3D, to: *const aiVector3D) void;

pub extern "c" fn aiMatrix4FromMatrix3(dst: *aiMatrix4x4, mat: *const aiMatrix3x3) void;
pub extern "c" fn aiMatrix4FromScalingQuaternionPosition(mat: *aiMatrix4x4, scaling: *const aiVector3D, rotation: *const aiQuaternion, position: *const aiVector3D) void;
pub extern "c" fn aiMatrix4Add(dst: *aiMatrix4x4, src: *const aiMatrix4x4) void;
pub extern "c" fn aiMatrix4AreEqual(a: *const aiMatrix4x4, b: *const aiMatrix4x4) c_int;
pub extern "c" fn aiMatrix4AreEqualEpsilon(a: *const aiMatrix4x4, b: *const aiMatrix4x4, epsilon: f32) c_int;
pub extern "c" fn aiMatrix4Inverse(mat: *aiMatrix4x4) void;
pub extern "c" fn aiMatrix4Determinant(mat: *const aiMatrix4x4) aiReal;
pub extern "c" fn aiMatrix4IsIdentity(mat: *const aiMatrix4x4) c_int;
pub extern "c" fn aiMatrix4DecomposeIntoScalingEulerAnglesPosition(mat: *const aiMatrix4x4, scaling: *aiVector3D, rotation: *aiVector3D, position: *aiVector3D) void;
pub extern "c" fn aiMatrix4DecomposeIntoScalingAxisAnglePosition(mat: *const aiMatrix4x4, scaling: *aiVector3D, axis: *aiVector3D, angle: *aiReal, position: *aiVector3D) void;
pub extern "c" fn aiMatrix4DecomposeNoScaling(mat: *const aiMatrix4x4, rotation: *aiQuaternion, position: *aiVector3D) void;
pub extern "c" fn aiMatrix4FromEulerAngles(mat: *aiMatrix4x4, x: aiReal, y: aiReal, z: aiReal) void;
pub extern "c" fn aiMatrix4RotationX(mat: *aiMatrix4x4, angle: aiReal) void;
pub extern "c" fn aiMatrix4RotationY(mat: *aiMatrix4x4, angle: aiReal) void;
pub extern "c" fn aiMatrix4RotationZ(mat: *aiMatrix4x4, angle: aiReal) void;
pub extern "c" fn aiMatrix4FromRotationAroundAxis(mat: *aiMatrix4x4, axis: *const aiVector3D, angle: aiReal) void;
pub extern "c" fn aiMatrix4Translation(mat: *aiMatrix4x4, translation: *const aiVector3D) void;
pub extern "c" fn aiMatrix4Scaling(mat: *aiMatrix4x4, scaling: *const aiVector3D) void;
pub extern "c" fn aiMatrix4FromTo(mat: *aiMatrix4x4, from: *const aiVector3D, to: *const aiVector3D) void;

pub extern "c" fn aiQuaternionFromEulerAngles(q: *aiQuaternion, x: aiReal, y: aiReal, z: aiReal) void;
pub extern "c" fn aiQuaternionFromAxisAngle(q: *aiQuaternion, axis: *const aiVector3D, angle: aiReal) void;
pub extern "c" fn aiQuaternionFromNormalizedQuaternion(q: *aiQuaternion, normalized: *const aiVector3D) void;
pub extern "c" fn aiQuaternionAreEqual(a: *const aiQuaternion, b: *const aiQuaternion) c_int;
pub extern "c" fn aiQuaternionAreEqualEpsilon(a: *const aiQuaternion, b: *const aiQuaternion, epsilon: f32) c_int;
pub extern "c" fn aiQuaternionNormalize(q: *aiQuaternion) void;
pub extern "c" fn aiQuaternionConjugate(q: *aiQuaternion) void;
pub extern "c" fn aiQuaternionMultiply(dst: *aiQuaternion, q: *const aiQuaternion) void;
pub extern "c" fn aiQuaternionInterpolate(dst: *aiQuaternion, start: *const aiQuaternion, end: *const aiQuaternion, factor: aiReal) void;

pub extern "c" fn aiGetLegalString() [*:0]const u8;
pub extern "c" fn aiGetVersionPatch() c_uint;
pub extern "c" fn aiGetVersionMinor() c_uint;
pub extern "c" fn aiGetVersionMajor() c_uint;
pub extern "c" fn aiGetVersionRevision() c_uint;
pub extern "c" fn aiGetBranchName() [*:0]const u8;
pub extern "c" fn aiGetCompileFlags() c_uint;

pub extern "c" fn aiGetExportFormatCount() usize;
pub extern "c" fn aiGetExportFormatDescription(pIndex: usize) ?*const aiExportFormatDesc;
pub extern "c" fn aiReleaseExportFormatDescription(desc: ?*const aiExportFormatDesc) void;
pub extern "c" fn aiExportScene(pScene: *const aiScene, pFormatId: [*:0]const u8, pFileName: [*:0]const u8, pPreprocessing: c_uint) aiReturn;
pub extern "c" fn aiExportSceneEx(pScene: *const aiScene, pFormatId: [*:0]const u8, pFileName: [*:0]const u8, pIO: ?*aiFileIO, pPreprocessing: c_uint) aiReturn;
pub extern "c" fn aiExportSceneToBlob(pScene: *const aiScene, pFormatId: [*:0]const u8, pPreprocessing: c_uint) ?*const aiExportDataBlob;
pub extern "c" fn aiReleaseExportBlob(pData: ?*const aiExportDataBlob) void;
pub extern "c" fn aiCopyScene(pIn: *const aiScene, pOut: *?*aiScene) void;
pub extern "c" fn aiFreeScene(pIn: ?*const aiScene) void;

pub extern "c" fn aiGetMaterialProperty(pMat: *const aiMaterial, pKey: [*:0]const u8, type_: c_uint, index: c_uint, pPropOut: *?*const aiMaterialProperty) aiReturn;
pub extern "c" fn aiGetMaterialFloatArray(pMat: *const aiMaterial, pKey: [*:0]const u8, type_: c_uint, index: c_uint, pOut: *aiReal, pMax: ?*c_uint) aiReturn;
pub extern "c" fn aiGetMaterialIntegerArray(pMat: *const aiMaterial, pKey: [*:0]const u8, type_: c_uint, index: c_uint, pOut: *c_int, pMax: ?*c_uint) aiReturn;
pub extern "c" fn aiGetMaterialColor(pMat: *const aiMaterial, pKey: [*:0]const u8, type_: c_uint, index: c_uint, pOut: *aiColor4D) aiReturn;
pub extern "c" fn aiGetMaterialUVTransform(pMat: *const aiMaterial, pKey: [*:0]const u8, type_: c_uint, index: c_uint, pOut: *types.aiUVTransform) aiReturn;
pub extern "c" fn aiGetMaterialString(pMat: *const aiMaterial, pKey: [*:0]const u8, type_: c_uint, index: c_uint, pOut: *aiString) aiReturn;
pub extern "c" fn aiGetMaterialTextureCount(pMat: *const aiMaterial, type_: aiTextureType) c_uint;
pub extern "c" fn aiGetMaterialTexture(pMat: *const aiMaterial, type_: aiTextureType, index: c_uint, path: *aiString, mapping: ?*types.aiTextureMapping, uvindex: ?*c_uint, blend: ?*aiReal, op: ?*types.aiTextureOp, mapmode: ?[*]types.aiTextureMapMode, flags: ?*c_uint) aiReturn;
pub extern "c" fn aiTextureTypeToString(in_: aiTextureType) [*:0]const u8;

pub extern "c" fn aiGetImporterDesc(extension: [*:0]const u8) ?*const aiImporterDesc;

const aiTextureType = types.aiTextureType;
const aiTextureMapping = types.aiTextureMapping;
const aiTextureOp = types.aiTextureOp;
const aiTextureMapMode = types.aiTextureMapMode;
const aiMaterialProperty = types.aiMaterialProperty;
